export const movies = {
    GETLISTMOVIE: 'GETLISTMOVIE',
    GETLISTMOVIE_SUCCESS: 'GETLISTMOVIE_SUCCESS',
    GETLISTMOVIE_FAILED: 'GETLISTMOVIE_FAILED',
}

export const detailMovies = {
    GETDETAILMOVIE: 'GETDETAILMOVIE',
    GETDETAILMOVIE_SUCCESS: 'GETDETAILMOVIE_SUCCESS',
    GETDETAILMOVIE_FAILED: 'GETDETAILMOVIE_FAILED'
}

